<?php

namespace MainBundle\Repository;

/**
 * DemandePartenariatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandePartenariatRepository extends \Doctrine\ORM\EntityRepository
{
}
