<?php

namespace MainBundle\Repository;

/**
 * EvaluationEtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationEtablissementRepository extends \Doctrine\ORM\EntityRepository
{
}
