<?php

namespace MainBundle\Repository;

/**
 * PartenariatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenariatRepository extends \Doctrine\ORM\EntityRepository
{
}
