<?php

namespace MainBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{

    public function chercherAdmin($q)
    {
        $qb = $this->createQueryBuilder('r'); // r est un alias de l'entit" reclamation
        $qb->where('r.sujet LIKE :q')
            ->orWhere('r.contenu_reclamation LIKE :q')
            ->setParameter('q', '%' . $q . '%');
        
        // si avec pagination
        return $qb;
    }
}
