<?php

namespace MainBundle\Repository;

/**
 * TableIndicationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TableIndicationsRepository extends \Doctrine\ORM\EntityRepository
{
}
